import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dua & Ruqayah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("bg-[#F7F8FA]", inter.className)}>
        <main className="p-10 h-screen">{children}</main>
      </body>
    </html>
  );
}
